### ISSUE TITLE
Not as claimed

### ISSUE THREAD

**Issue by 2helpinghand7** [Greenwolf/social_mapper#149]
I have run social mapper in kali Linux. To my surprise it doesn't deliver the expected result.
1. facebook login has limitation
2. if i renamed billgate.jpg as renew.jpg it does not fetch any result. 
it claims to be a face recognition application rather we found this to be more profile name related search

**Comment by rafe-ai** [comment]
>     2. if i renamed billgate.jpg as renew.jpg it does not fetch any result.
>        it claims to be a face recognition application rather we found this to be more profile name related search

I don't think it works that way. I understand why you would think that, because of the way some websites present this tool. For example they say: Social Mapper — Find Social Media Profiles Using Only a Photo.
What is does is, it finds profiles based on the name of the picture. Then it uses facial recognition to decide which of all the Bill Gates-es found is the one that you are looking for.
It would take a LONG time to check everybody who's on fb etc.

**Comment by Greenwolf** [comment]
@rafe-ai is correct, closing this
