### ISSUE TITLE
im trying to find my facebook profile from my picture

### ISSUE THREAD

**Issue by azamet90** [Greenwolf/social_mapper#181]
but i get zero result? and the other problem is;
if i download the image from tom cruise and use it with the image title "tom cruise" it find somethings which is still not correct but if i change the image name to "dddd" it finds nothing :D why this is happening?

**Comment by Greenwolf** [comment]
You can't use your own Facebook profile to search, if your using a 2nd account maybe your main account isn't public or high ranked enough, you may have a very common name.

dddd finds nothing because it searches for name first to narrow it down, then does facial recognition on the smaller results set.
